sudo pacman -S git 
sudo pacman -S firefox
sudo pacman -S virtualbox
sudo pacman -S libreoffice
sudo pacman -S terminator 
sudo pacman -S gimp
sudo pacman -S VLC
sudo pacman -S gparted 
sudo pacman -S thunderbird 
sudo pacman -S unzip 
sudo pacman -S ufw 
sudo pacman -S openvpn 
sudo pacman -S networkmanager 
